from typing import Any, Self
from pydantic import ModelWrapValidatorHandler, PrivateAttr, model_validator
from pydantic import BaseModel, ConfigDict, Field

class DisplayPriorities(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    ae: int | Any = Field(None, alias='AE', union_mode='left_to_right')
    ar: int | Any = Field(None, alias='AR', union_mode='left_to_right')
    at: int | Any = Field(None, alias='AT', union_mode='left_to_right')
    au: int | Any = Field(None, alias='AU', union_mode='left_to_right')
    be: int | Any = Field(None, alias='BE', union_mode='left_to_right')
    bg: int | Any = Field(None, alias='BG', union_mode='left_to_right')
    bo: int | Any = Field(None, alias='BO', union_mode='left_to_right')
    br: int | Any = Field(None, alias='BR', union_mode='left_to_right')
    by: int | Any = Field(None, alias='BY', union_mode='left_to_right')
    bz: int | Any = Field(None, alias='BZ', union_mode='left_to_right')
    ca: int | Any = Field(None, alias='CA', union_mode='left_to_right')
    ch: int | Any = Field(None, alias='CH', union_mode='left_to_right')
    cl: int | Any = Field(None, alias='CL', union_mode='left_to_right')
    co: int | Any = Field(None, alias='CO', union_mode='left_to_right')
    cr: int | Any = Field(None, alias='CR', union_mode='left_to_right')
    cy: int | Any = Field(None, alias='CY', union_mode='left_to_right')
    cz: int | Any = Field(None, alias='CZ', union_mode='left_to_right')
    cv: int | Any = Field(None, alias='CV', union_mode='left_to_right')
    de: int | Any = Field(None, alias='DE', union_mode='left_to_right')
    dk: int | Any = Field(None, alias='DK', union_mode='left_to_right')
    ec: int | Any = Field(None, alias='EC', union_mode='left_to_right')
    ee: int | Any = Field(None, alias='EE', union_mode='left_to_right')
    eg: int | Any = Field(None, alias='EG', union_mode='left_to_right')
    es: int | Any = Field(None, alias='ES', union_mode='left_to_right')
    fi: int | Any = Field(None, alias='FI', union_mode='left_to_right')
    fr: int | Any = Field(None, alias='FR', union_mode='left_to_right')
    gb: int | Any = Field(None, alias='GB', union_mode='left_to_right')
    gh: int | Any = Field(None, alias='GH', union_mode='left_to_right')
    gr: int | Any = Field(None, alias='GR', union_mode='left_to_right')
    gt: int | Any = Field(None, alias='GT', union_mode='left_to_right')
    hk: int | Any = Field(None, alias='HK', union_mode='left_to_right')
    hn: int | Any = Field(None, alias='HN', union_mode='left_to_right')
    hu: int | Any = Field(None, alias='HU', union_mode='left_to_right')
    id: int | Any = Field(None, alias='ID', union_mode='left_to_right')
    ie: int | Any = Field(None, alias='IE', union_mode='left_to_right')
    in_: int | Any = Field(None, alias='IN', union_mode='left_to_right')
    il: int | Any = Field(None, alias='IL', union_mode='left_to_right')
    it: int | Any = Field(None, alias='IT', union_mode='left_to_right')
    jp: int | Any = Field(None, alias='JP', union_mode='left_to_right')
    lu: int | Any = Field(None, alias='LU', union_mode='left_to_right')
    lt: int | Any = Field(None, alias='LT', union_mode='left_to_right')
    lv: int | Any = Field(None, alias='LV', union_mode='left_to_right')
    mu: int | Any = Field(None, alias='MU', union_mode='left_to_right')
    mx: int | Any = Field(None, alias='MX', union_mode='left_to_right')
    my: int | Any = Field(None, alias='MY', union_mode='left_to_right')
    mz: int | Any = Field(None, alias='MZ', union_mode='left_to_right')
    ni: int | Any = Field(None, alias='NI', union_mode='left_to_right')
    nl: int | Any = Field(None, alias='NL', union_mode='left_to_right')
    no: int | Any = Field(None, alias='NO', union_mode='left_to_right')
    nz: int | Any = Field(None, alias='NZ', union_mode='left_to_right')
    pe: int | Any = Field(None, alias='PE', union_mode='left_to_right')
    pl: int | Any = Field(None, alias='PL', union_mode='left_to_right')
    ph: int | Any = Field(None, alias='PH', union_mode='left_to_right')
    pt: int | Any = Field(None, alias='PT', union_mode='left_to_right')
    py: int | Any = Field(None, alias='PY', union_mode='left_to_right')
    ru: int | Any = Field(None, alias='RU', union_mode='left_to_right')
    sa: int | Any = Field(None, alias='SA', union_mode='left_to_right')
    sg: int | Any = Field(None, alias='SG', union_mode='left_to_right')
    se: int | Any = Field(None, alias='SE', union_mode='left_to_right')
    si: int | Any = Field(None, alias='SI', union_mode='left_to_right')
    sk: int | Any = Field(None, alias='SK', union_mode='left_to_right')
    th: int | Any = Field(None, alias='TH', union_mode='left_to_right')
    tr: int | Any = Field(None, alias='TR', union_mode='left_to_right')
    tw: int | Any = Field(None, alias='TW', union_mode='left_to_right')
    ua: int | Any = Field(None, alias='UA', union_mode='left_to_right')
    ug: int | Any = Field(None, alias='UG', union_mode='left_to_right')
    us: int | Any = Field(None, alias='US', union_mode='left_to_right')
    ve: int | Any = Field(None, alias='VE', union_mode='left_to_right')
    za: int | Any = Field(None, alias='ZA', union_mode='left_to_right')
    ao: int | Any = Field(None, alias='AO', union_mode='left_to_right')
    az: int | Any = Field(None, alias='AZ', union_mode='left_to_right')
    bf: int | Any = Field(None, alias='BF', union_mode='left_to_right')
    hr: int | Any = Field(None, alias='HR', union_mode='left_to_right')
    is_: int | Any = Field(None, alias='IS', union_mode='left_to_right')
    kr: int | Any = Field(None, alias='KR', union_mode='left_to_right')
    ml: int | Any = Field(None, alias='ML', union_mode='left_to_right')
    pg: int | Any = Field(None, alias='PG', union_mode='left_to_right')
    tz: int | Any = Field(None, alias='TZ', union_mode='left_to_right')
    zw: int | Any = Field(None, alias='ZW', union_mode='left_to_right')
    ad: int | Any = Field(None, alias='AD', union_mode='left_to_right')
    ag: int | Any = Field(None, alias='AG', union_mode='left_to_right')
    al: int | Any = Field(None, alias='AL', union_mode='left_to_right')
    ba: int | Any = Field(None, alias='BA', union_mode='left_to_right')
    bb: int | Any = Field(None, alias='BB', union_mode='left_to_right')
    bh: int | Any = Field(None, alias='BH', union_mode='left_to_right')
    bm: int | Any = Field(None, alias='BM', union_mode='left_to_right')
    bs: int | Any = Field(None, alias='BS', union_mode='left_to_right')
    ci: int | Any = Field(None, alias='CI', union_mode='left_to_right')
    cm: int | Any = Field(None, alias='CM', union_mode='left_to_right')
    cu: int | Any = Field(None, alias='CU', union_mode='left_to_right')
    do: int | Any = Field(None, alias='DO', union_mode='left_to_right')
    dz: int | Any = Field(None, alias='DZ', union_mode='left_to_right')
    fj: int | Any = Field(None, alias='FJ', union_mode='left_to_right')
    gf: int | Any = Field(None, alias='GF', union_mode='left_to_right')
    gg: int | Any = Field(None, alias='GG', union_mode='left_to_right')
    gi: int | Any = Field(None, alias='GI', union_mode='left_to_right')
    gq: int | Any = Field(None, alias='GQ', union_mode='left_to_right')
    iq: int | Any = Field(None, alias='IQ', union_mode='left_to_right')
    jm: int | Any = Field(None, alias='JM', union_mode='left_to_right')
    jo: int | Any = Field(None, alias='JO', union_mode='left_to_right')
    ke: int | Any = Field(None, alias='KE', union_mode='left_to_right')
    kw: int | Any = Field(None, alias='KW', union_mode='left_to_right')
    lb: int | Any = Field(None, alias='LB', union_mode='left_to_right')
    lc: int | Any = Field(None, alias='LC', union_mode='left_to_right')
    li: int | Any = Field(None, alias='LI', union_mode='left_to_right')
    ma: int | Any = Field(None, alias='MA', union_mode='left_to_right')
    ly: int | Any = Field(None, alias='LY', union_mode='left_to_right')
    mc: int | Any = Field(None, alias='MC', union_mode='left_to_right')
    me: int | Any = Field(None, alias='ME', union_mode='left_to_right')
    md: int | Any = Field(None, alias='MD', union_mode='left_to_right')
    mg: int | Any = Field(None, alias='MG', union_mode='left_to_right')
    mk: int | Any = Field(None, alias='MK', union_mode='left_to_right')
    mt: int | Any = Field(None, alias='MT', union_mode='left_to_right')
    ne: int | Any = Field(None, alias='NE', union_mode='left_to_right')
    ng: int | Any = Field(None, alias='NG', union_mode='left_to_right')
    om: int | Any = Field(None, alias='OM', union_mode='left_to_right')
    pa: int | Any = Field(None, alias='PA', union_mode='left_to_right')
    pk: int | Any = Field(None, alias='PK', union_mode='left_to_right')
    pf: int | Any = Field(None, alias='PF', union_mode='left_to_right')
    ps: int | Any = Field(None, alias='PS', union_mode='left_to_right')
    qa: int | Any = Field(None, alias='QA', union_mode='left_to_right')
    ro: int | Any = Field(None, alias='RO', union_mode='left_to_right')
    rs: int | Any = Field(None, alias='RS', union_mode='left_to_right')
    sc: int | Any = Field(None, alias='SC', union_mode='left_to_right')
    sn: int | Any = Field(None, alias='SN', union_mode='left_to_right')
    sv: int | Any = Field(None, alias='SV', union_mode='left_to_right')
    sm: int | Any = Field(None, alias='SM', union_mode='left_to_right')
    tc: int | Any = Field(None, alias='TC', union_mode='left_to_right')
    td: int | Any = Field(None, alias='TD', union_mode='left_to_right')
    tn: int | Any = Field(None, alias='TN', union_mode='left_to_right')
    tt: int | Any = Field(None, alias='TT', union_mode='left_to_right')
    uy: int | Any = Field(None, alias='UY', union_mode='left_to_right')
    ye: int | Any = Field(None, alias='YE', union_mode='left_to_right')
    zm: int | Any = Field(None, alias='ZM', union_mode='left_to_right')
    cd: int | Any = Field(None, alias='CD', union_mode='left_to_right')
    gy: int | Any = Field(None, alias='GY', union_mode='left_to_right')
    mw: int | Any = Field(None, alias='MW', union_mode='left_to_right')
    va: int | Any = Field(None, alias='VA', union_mode='left_to_right')
    xk: int | Any = Field(None, alias='XK', union_mode='left_to_right')
    gp: int | Any = Field(None, alias='GP', union_mode='left_to_right')

class Result(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    display_priorities: DisplayPriorities | Any = Field(default=None, union_mode='left_to_right')
    display_priority: int | Any = Field(default=None, union_mode='left_to_right')
    logo_path: str | Any = Field(default=None, union_mode='left_to_right')
    provider_name: str | Any = Field(default=None, union_mode='left_to_right')
    provider_id: int | Any = Field(default=None, union_mode='left_to_right')

class WatchProvidersMovieListModel(BaseModel):
    model_config = ConfigDict(extra='ignore', defer_build=True)
    results: list[Result] | Any = Field(default=None, union_mode='left_to_right')
    _raw_input: Any = PrivateAttr(default=None)

    @model_validator(mode='wrap')
    @classmethod
    def _capture_raw_input(cls, data: Any, handler: ModelWrapValidatorHandler[Self]) -> Self:
        """Validate the model and keep the input it was built from."""
        model = handler(data)
        model._raw_input = data
        return model

    @property
    def raw_input(self) -> Any:
        """The input this model was validated from, as it was handed over."""
        return self._raw_input
