from typing import Any, Self
from pydantic import ModelWrapValidatorHandler, PrivateAttr, model_validator
from pydantic import ConfigDict
from pydantic import BaseModel, Field

class DisplayPriorities(BaseModel):
    model_config = ConfigDict(defer_build=True)
    ae: int | None = Field(None, alias='AE')
    ar: int | None = Field(None, alias='AR')
    at: int | None = Field(None, alias='AT')
    au: int | None = Field(None, alias='AU')
    be: int | None = Field(None, alias='BE')
    bg: int | None = Field(None, alias='BG')
    bo: int | None = Field(None, alias='BO')
    br: int | None = Field(None, alias='BR')
    by: int | None = Field(None, alias='BY')
    bz: int | None = Field(None, alias='BZ')
    ca: int | None = Field(None, alias='CA')
    ch: int | None = Field(None, alias='CH')
    cl: int | None = Field(None, alias='CL')
    co: int | None = Field(None, alias='CO')
    cr: int | None = Field(None, alias='CR')
    cy: int | None = Field(None, alias='CY')
    cz: int | None = Field(None, alias='CZ')
    cv: int | None = Field(None, alias='CV')
    de: int | None = Field(None, alias='DE')
    dk: int | None = Field(None, alias='DK')
    ec: int | None = Field(None, alias='EC')
    ee: int | None = Field(None, alias='EE')
    eg: int | None = Field(None, alias='EG')
    es: int | None = Field(None, alias='ES')
    fi: int | None = Field(None, alias='FI')
    fr: int | None = Field(None, alias='FR')
    gb: int | None = Field(None, alias='GB')
    gh: int | None = Field(None, alias='GH')
    gr: int | None = Field(None, alias='GR')
    gt: int | None = Field(None, alias='GT')
    hk: int | None = Field(None, alias='HK')
    hn: int | None = Field(None, alias='HN')
    hu: int | None = Field(None, alias='HU')
    id: int | None = Field(None, alias='ID')
    ie: int | None = Field(None, alias='IE')
    in_: int | None = Field(None, alias='IN')
    il: int | None = Field(None, alias='IL')
    it: int | None = Field(None, alias='IT')
    jp: int | None = Field(None, alias='JP')
    lu: int | None = Field(None, alias='LU')
    lt: int | None = Field(None, alias='LT')
    lv: int | None = Field(None, alias='LV')
    mu: int | None = Field(None, alias='MU')
    mx: int | None = Field(None, alias='MX')
    my: int | None = Field(None, alias='MY')
    mz: int | None = Field(None, alias='MZ')
    ni: int | None = Field(None, alias='NI')
    nl: int | None = Field(None, alias='NL')
    no: int | None = Field(None, alias='NO')
    nz: int | None = Field(None, alias='NZ')
    pe: int | None = Field(None, alias='PE')
    pl: int | None = Field(None, alias='PL')
    ph: int | None = Field(None, alias='PH')
    pt: int | None = Field(None, alias='PT')
    py: int | None = Field(None, alias='PY')
    ru: int | None = Field(None, alias='RU')
    sa: int | None = Field(None, alias='SA')
    sg: int | None = Field(None, alias='SG')
    se: int | None = Field(None, alias='SE')
    si: int | None = Field(None, alias='SI')
    sk: int | None = Field(None, alias='SK')
    th: int | None = Field(None, alias='TH')
    tr: int | None = Field(None, alias='TR')
    tw: int | None = Field(None, alias='TW')
    ua: int | None = Field(None, alias='UA')
    ug: int | None = Field(None, alias='UG')
    us: int | None = Field(None, alias='US')
    ve: int | None = Field(None, alias='VE')
    za: int | None = Field(None, alias='ZA')
    ao: int | None = Field(None, alias='AO')
    az: int | None = Field(None, alias='AZ')
    bf: int | None = Field(None, alias='BF')
    hr: int | None = Field(None, alias='HR')
    is_: int | None = Field(None, alias='IS')
    kr: int | None = Field(None, alias='KR')
    ml: int | None = Field(None, alias='ML')
    pg: int | None = Field(None, alias='PG')
    tz: int | None = Field(None, alias='TZ')
    zw: int | None = Field(None, alias='ZW')
    ad: int | None = Field(None, alias='AD')
    ag: int | None = Field(None, alias='AG')
    al: int | None = Field(None, alias='AL')
    ba: int | None = Field(None, alias='BA')
    bb: int | None = Field(None, alias='BB')
    bh: int | None = Field(None, alias='BH')
    bm: int | None = Field(None, alias='BM')
    bs: int | None = Field(None, alias='BS')
    ci: int | None = Field(None, alias='CI')
    cm: int | None = Field(None, alias='CM')
    cu: int | None = Field(None, alias='CU')
    do: int | None = Field(None, alias='DO')
    dz: int | None = Field(None, alias='DZ')
    fj: int | None = Field(None, alias='FJ')
    gf: int | None = Field(None, alias='GF')
    gg: int | None = Field(None, alias='GG')
    gi: int | None = Field(None, alias='GI')
    gq: int | None = Field(None, alias='GQ')
    iq: int | None = Field(None, alias='IQ')
    jm: int | None = Field(None, alias='JM')
    jo: int | None = Field(None, alias='JO')
    ke: int | None = Field(None, alias='KE')
    kw: int | None = Field(None, alias='KW')
    lb: int | None = Field(None, alias='LB')
    lc: int | None = Field(None, alias='LC')
    li: int | None = Field(None, alias='LI')
    ma: int | None = Field(None, alias='MA')
    ly: int | None = Field(None, alias='LY')
    mc: int | None = Field(None, alias='MC')
    me: int | None = Field(None, alias='ME')
    md: int | None = Field(None, alias='MD')
    mg: int | None = Field(None, alias='MG')
    mk: int | None = Field(None, alias='MK')
    mt: int | None = Field(None, alias='MT')
    ne: int | None = Field(None, alias='NE')
    ng: int | None = Field(None, alias='NG')
    om: int | None = Field(None, alias='OM')
    pa: int | None = Field(None, alias='PA')
    pk: int | None = Field(None, alias='PK')
    pf: int | None = Field(None, alias='PF')
    ps: int | None = Field(None, alias='PS')
    qa: int | None = Field(None, alias='QA')
    ro: int | None = Field(None, alias='RO')
    rs: int | None = Field(None, alias='RS')
    sc: int | None = Field(None, alias='SC')
    sn: int | None = Field(None, alias='SN')
    sv: int | None = Field(None, alias='SV')
    sm: int | None = Field(None, alias='SM')
    tc: int | None = Field(None, alias='TC')
    td: int | None = Field(None, alias='TD')
    tn: int | None = Field(None, alias='TN')
    tt: int | None = Field(None, alias='TT')
    uy: int | None = Field(None, alias='UY')
    ye: int | None = Field(None, alias='YE')
    zm: int | None = Field(None, alias='ZM')
    cd: int | None = Field(None, alias='CD')
    gy: int | None = Field(None, alias='GY')
    mw: int | None = Field(None, alias='MW')
    va: int | None = Field(None, alias='VA')
    xk: int | None = Field(None, alias='XK')
    gp: int | None = Field(None, alias='GP')

class Result(BaseModel):
    model_config = ConfigDict(defer_build=True)
    display_priorities: DisplayPriorities
    display_priority: int
    logo_path: str
    provider_name: str
    provider_id: int

class WatchProvidersMovieListModel(BaseModel):
    model_config = ConfigDict(defer_build=True)
    results: list[Result]
    _raw_input: Any = PrivateAttr(default=None)

    @model_validator(mode='wrap')
    @classmethod
    def _capture_raw_input(cls, data: Any, handler: ModelWrapValidatorHandler[Self]) -> Self:
        """Validate the model and keep the input it was built from."""
        model = handler(data)
        model._raw_input = data
        return model

    @property
    def raw_input(self) -> Any:
        """The input this model was validated from, as it was handed over."""
        return self._raw_input
